title: Unicorn poop
hero_image: images/banner.png
description: Create a colourful website with shapes, gradients, and a scrolling ticker.
listed: false
pdf: false
landing: true
steps:
  - title: Step 1
  - title: Step 2
    completion:
      - engaged
  - title: Step 3
  - title: Step 4
  - title: Step 5
  - title: Step 6
    completion:
      - internal
  - title: Step 7
  - title: Step 8
  - title: Step 9
    challenge: true
  - title: Step 10
    challenge: true